# BEST PRACTICES:
# -------------------------------------------------------------------------------------------------------------


# PEP8==> GUIDE LINE  # [ WEB SEARCH PEP8 AND FOLLOW GUIDELINES ]




# SNAKE CASE NAMING CONVERSION
# FIRSTNAME    ->     X
# FIRST_NAME   ->     SNAKE




# MODULES, FUNCTION,VARIABLE===> SHOULD START WITH LOWER CASE




# CLASS===> SHOULD START WITH UPPERCASE




# _ ==> for_in range(1 0):    [ use of underscore ]
#       print(_)




# CONTANT VARIABLE SHULD BE IN UPPERCASE.




# MEANINGFULL OF VARIABLE.




# COMMENT




# DOC STRING.....